name: The Real FA Cup
title: The Real FA Cup
title_separator: "|"
email: admin@therealfacup.co.uk
baseurl: ""
url: "https://www.therealfacup.co.uk"

# Build settings
theme: minimal-mistakes-jekyll
# minimal_mistakes_skin: "dark"
plugins:
  - jekyll-feed
  - jekyll-include-cache
atom_feed:
  hide: true
search: true
include: ["_pages"]
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/therealfacup"
    - label: "Email"
      icon: "far fa-fw fa-envelope"
      url: "mailto:admin@therealfacup.co.uk"
paginate: 5
timezone: Europe/London
collections:
  portfolio:
    output: true
    permalink: /:collection/:path/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      show_date: true
      comments: true
      share: true
      related: true
      classes: wide
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      classes: wide
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      classes: wide

comments:
  provider: "disqus"
  disqus:
    shortname: "therealfacup"
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
